FROM golang

RUN mkdir -p /go/src/github.com/learning/project/api
WORKDIR /go/src/github.com/learning/project/api

COPY ./ ./
RUN make install
RUN go build -o bin/api main.go

CMD ["/go/src/github.com/learning/project/api/bin/api"]