
install:
	go get -u github.com/gorilla/mux
	go get -u github.com/gorilla/handlers
	go get -u github.com/go-xorm/xorm
	go get -u github.com/go-sql-driver/mysql
	go get -u golang.org/x/crypto/bcrypt
	go get -u github.com/dgrijalva/jwt-go
